# Generated by Django 4.2 on 2024-04-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='number',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
    ]
